export const SELECT_HOUSELIST_REQUEST = 'SELECT_HOUSELIST_REQUEST';
export const SELECT_HOUSELIST_SUCCESS = 'SELECT_HOUSELIST_SUCCESS';
export const SELECT_HOUSELIST_FAILURE = 'SELECT_HOUSELIST_FAILURE';
export const RESET_HOUSELIST_STATE = 'RESET_HOUSELIST_STATE';

export const SELECT_HOTHOUSENEW_REQUEST = 'SELECT_HOTHOUSENEW_REQUEST';
export const SELECT_HOTHOUSENEW_SUCCESS = 'SELECT_HOTHOUSENEW_SUCCESS';
export const SELECT_HOTHOUSENEW_FAILURE = 'SELECT_HOTHOUSENEW_FAILURE';

export const SELECT_HOTHOUSESECOND_REQUEST = 'SELECT_HOTHOUSESECOND_REQUEST';
export const SELECT_HOTHOUSESECOND_SUCCESS = 'SELECT_HOTHOUSESECOND_SUCCESS';
export const SELECT_HOTHOUSESECOND_FAILURE = 'SELECT_HOTHOUSESECOND_FAILURE';

export const SELECT_HOTHOUSERENT_REQUEST = 'SELECT_HOTHOUSERENT_REQUEST';
export const SELECT_HOTHOUSERENT_SUCCESS = 'SELECT_HOTHOUSERENT_SUCCESS';
export const SELECT_HOTHOUSERENT_FAILURE = 'SELECT_HOTHOUSERENT_FAILURE';

export const SELECT_HOTHOUSE_REQUEST = 'SELECT_HOTHOUSE_REQUEST';
export const SELECT_HOTHOUSE_SUCCESS = 'SELECT_HOTHOUSE_SUCCESS';
export const SELECT_HOTHOUSE_FAILURE = 'SELECT_HOTHOUSE_FAILURE';

export const SELECT_HOUSEHISTORY_REQUEST = 'SELECT_HOUSEHISTORY_REQUEST';
export const SELECT_HOUSEHISTORY_SUCCESS = 'SELECT_HOUSEHISTORY_SUCCESS';
export const SELECT_HOUSEHISTORY_FAILURE = 'SELECT_HOUSEHISTORY_FAILURE';
export const RESET_HOUSEHISTORY_STATE = 'RESET_HOUSEHISTORY_STATE';

export const SELECT_HOUSEDETAIL_REQUEST = 'SELECT_HOUSEDETAIL_REQUEST';
export const SELECT_HOUSEDETAIL_SUCCESS = 'SELECT_HOUSEDETAIL_SUCCESS';
export const SELECT_HOUSEDETAIL_FAILURE = 'SELECT_HOUSEDETAIL_FAILURE';

export const UPDATE_HOUSEFOLLOW_REQUEST = 'UPDATE_HOUSEFOLLOW_REQUEST';
export const UPDATE_HOUSEFOLLOW_SUCCESS = 'UPDATE_HOUSEFOLLOW_SUCCESS';
export const UPDATE_HOUSEFOLLOW_FAILURE = 'UPDATE_HOUSEFOLLOW_FAILURE';

export const UPDATE_HOUSEUNFOLLOW_REQUEST = 'UPDATE_HOUSEUNFOLLOW_REQUEST';
export const UPDATE_HOUSEUNFOLLOW_SUCCESS = 'UPDATE_HOUSEUNFOLLOW_SUCCESS';
export const UPDATE_HOUSEUNFOLLOW_FAILURE = 'UPDATE_HOUSEUNFOLLOW_FAILURE';

export const SELECT_HOUSEFAVORITERENT_REQUEST = 'SELECT_HOUSEFAVORITERENT_REQUEST';
export const SELECT_HOUSEFAVORITERENT_SUCCESS = 'SELECT_HOUSEFAVORITERENT_SUCCESS';
export const SELECT_HOUSEFAVORITERENT_FAILURE = 'SELECT_HOUSEFAVORITERENT_FAILURE';
export const SELECT_HOUSEFAVORITESECOND_REQUEST = 'SELECT_HOUSEFAVORITESECOND_REQUEST';
export const SELECT_HOUSEFAVORITESECOND_SUCCESS = 'SELECT_HOUSEFAVORITESECOND_SUCCESS';
export const SELECT_HOUSEFAVORITESECOND_FAILURE = 'SELECT_HOUSEFAVORITESECOND_FAILURE';
export const SELECT_HOUSEFAVORITENEW_REQUEST = 'SELECT_HOUSEFAVORITENEW_REQUEST';
export const SELECT_HOUSEFAVORITENEW_SUCCESS = 'SELECT_HOUSEFAVORITENEW_SUCCESS';
export const SELECT_HOUSEFAVORITENEW_FAILURE = 'SELECT_HOUSEFAVORITENEW_FAILURE';
export const RESET_HOUSEFAVORITE_STATE = 'RESET_HOUSEFAVORITE_STATE';
