export const SELECT_HOUSE_REQUEST = 'SELECT_HOUSE_REQUEST';
export const SELECT_HOUSE_SUCCESS = 'SELECT_HOUSE_SUCCESS';
export const SELECT_HOUSE_FAILURE = 'SELECT_HOUSE_FAILURE';
export const REMOVE_HOUSE_REPLACE = 'REMOVE_HOUSE_REPLACE';

export const SELECT_HOTHOUSE_REQUEST = 'SELECT_HOTHOUSE_REQUEST';
export const SELECT_HOTHOUSE_SUCCESS = 'SELECT_HOTHOUSE_SUCCESS';
export const SELECT_HOTHOUSE_FAILURE = 'SELECT_HOTHOUSE_FAILURE';

export const SELECT_HISTORY_REQUEST = 'SELECT_HISTORY_REQUEST';
export const SELECT_HISTORY_SUCCESS = 'SELECT_HISTORY_SUCCESS';
export const SELECT_HISTORY_FAILURE = 'SELECT_HISTORY_FAILURE';
export const REMOVE_HISTORY_REPLACE = 'REMOVE_HISTORY_REPLACE';

export const SELECT_DETAIL_REQUEST = 'SELECT_DETAIL_REQUEST';
export const SELECT_DETAIL_SUCCESS = 'SELECT_DETAIL_SUCCESS';
export const SELECT_DETAIL_FAILURE = 'SELECT_DETAIL_FAILURE';
export const SELECT_DETAIL_REPLACE = 'SELECT_DETAIL_REPLACE';

export const UPDATE_FOLLOW_REQUEST = 'UPDATE_FOLLOW_REQUEST';
export const UPDATE_FOLLOW_SUCCESS = 'UPDATE_FOLLOW_SUCCESS';
export const UPDATE_FOLLOW_FAILURE = 'UPDATE_FOLLOW_FAILURE';

export const UPDATE_UNFOLLOW_REQUEST = 'UPDATE_UNFOLLOW_REQUEST';
export const UPDATE_UNFOLLOW_SUCCESS = 'UPDATE_UNFOLLOW_SUCCESS';
export const UPDATE_UNFOLLOW_FAILURE = 'UPDATE_UNFOLLOW_FAILURE';

export const SELECT_CITYS_REQUEST = 'SELECT_CITYS_REQUEST';
export const SELECT_CITYS_SUCCESS = 'SELECT_CITYS_SUCCESS';
export const SELECT_CITYS_FAILURE = 'SELECT_CITYS_FAILURE';
export const UPDATE_CITYS_REPLACE = 'UPDATE_CITYS_REPLACE';

export const SELECT_AREAS_REQUEST = 'SELECT_AREAS_REQUEST';
export const SELECT_AREAS_SUCCESS = 'SELECT_AREAS_SUCCESS';
export const SELECT_AREAS_FAILURE = 'SELECT_AREAS_FAILURE';

export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST';
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS';
export const SELECT_LOGIN_FAILURE = 'SELECT_LOGIN_FAILURE';

export const SELECT_PHONE_REQUEST = 'SELECT_PHONE_REQUEST';
export const SELECT_PHONE_SUCCESS = 'SELECT_PHONE_SUCCESS';
export const SELECT_PHONE_FAILURE = 'SELECT_PHONE_FAILURE';
export const SELECT_PHONE_REPLACE = 'SELECT_PHONE_REPLACE';

export const SELECT_FAVORITE_REQUEST = 'SELECT_FAVORITE_REQUEST';
export const SELECT_FAVORITE_SUCCESS = 'SELECT_FAVORITE_SUCCESS';
export const SELECT_FAVORITE_FAILURE = 'SELECT_FAVORITE_FAILURE';
export const REMOVE_FAVORITE_REPLACE = 'REMOVE_FAVORITE_REPLACE';
