"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SELECT_HOUSEDETAIL_FAILURE = exports.SELECT_HOUSEDETAIL_SUCCESS = exports.SELECT_HOUSEDETAIL_REQUEST = exports.RESET_RENTHOUSELIST_STATE = exports.SELECT_RENTHOUSELIST_FAILURE = exports.SELECT_RENTHOUSELIST_SUCCESS = exports.SELECT_RENTHOUSELIST_REQUEST = void 0;
var SELECT_RENTHOUSELIST_REQUEST = 'SELECT_RENTHOUSELIST_REQUEST';
exports.SELECT_RENTHOUSELIST_REQUEST = SELECT_RENTHOUSELIST_REQUEST;
var SELECT_RENTHOUSELIST_SUCCESS = 'SELECT_RENTHOUSELIST_SUCCESS';
exports.SELECT_RENTHOUSELIST_SUCCESS = SELECT_RENTHOUSELIST_SUCCESS;
var SELECT_RENTHOUSELIST_FAILURE = 'SELECT_RENTHOUSELIST_FAILURE';
exports.SELECT_RENTHOUSELIST_FAILURE = SELECT_RENTHOUSELIST_FAILURE;
var RESET_RENTHOUSELIST_STATE = 'RESET_RENTHOUSELIST_STATE';
exports.RESET_RENTHOUSELIST_STATE = RESET_RENTHOUSELIST_STATE;
var SELECT_HOUSEDETAIL_REQUEST = 'SELECT_HOUSEDETAIL_REQUEST';
exports.SELECT_HOUSEDETAIL_REQUEST = SELECT_HOUSEDETAIL_REQUEST;
var SELECT_HOUSEDETAIL_SUCCESS = 'SELECT_HOUSEDETAIL_SUCCESS';
exports.SELECT_HOUSEDETAIL_SUCCESS = SELECT_HOUSEDETAIL_SUCCESS;
var SELECT_HOUSEDETAIL_FAILURE = 'SELECT_HOUSEDETAIL_FAILURE';
exports.SELECT_HOUSEDETAIL_FAILURE = SELECT_HOUSEDETAIL_FAILURE;