"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SELECT_PRODUCT_FAILURE = exports.SELECT_PRODUCT_SUCCESS = exports.SELECT_PRODUCT_REQUEST = exports.SELECT_QRCODE_FAILURE = exports.SELECT_QRCODE_SUCCESS = exports.SELECT_QRCODE_REQUEST = void 0;
var SELECT_QRCODE_REQUEST = 'SELECT_QRCODE_REQUEST';
exports.SELECT_QRCODE_REQUEST = SELECT_QRCODE_REQUEST;
var SELECT_QRCODE_SUCCESS = 'SELECT_QRCODE_SUCCESS';
exports.SELECT_QRCODE_SUCCESS = SELECT_QRCODE_SUCCESS;
var SELECT_QRCODE_FAILURE = 'SELECT_QRCODE_FAILURE';
exports.SELECT_QRCODE_FAILURE = SELECT_QRCODE_FAILURE;
var SELECT_PRODUCT_REQUEST = 'SELECT_PRODUCT_REQUEST';
exports.SELECT_PRODUCT_REQUEST = SELECT_PRODUCT_REQUEST;
var SELECT_PRODUCT_SUCCESS = 'SELECT_PRODUCT_SUCCESS';
exports.SELECT_PRODUCT_SUCCESS = SELECT_PRODUCT_SUCCESS;
var SELECT_PRODUCT_FAILURE = 'SELECT_PRODUCT_FAILURE';
exports.SELECT_PRODUCT_FAILURE = SELECT_PRODUCT_FAILURE;